### ISSUE TITLE
From form: Downloading failures for pecan 1.7.0 and 1.60

### ISSUE THREAD

**Issue by rahul799** [PecanProject/PecanProject.github.io#15]
I am trying to download pecan on to a portable thumb drive (has 116 GB of space) to create a pecan virtual machine for my windows PC. Every time I've downloaded Pecan from https://opensource.ncsa.illinois.edu/projects/artifacts.php?key=PECAN, I get an error at about 4 MB into the download, and at other times, have had the download stop right before reaching the 8 GB of version 1.7.0. What can I do to download pecan successfully onto a thumb drive?

*This issue was autogenerated by the Google Form for [Features](https://docs.google.com/forms/d/e/1FAIpQLSdRNat6L9grRF0xU5gibkr26xq9jD9wyHgw_AWxhrgn0lWv7w/viewform)*

Name: Michael Najarro

Email: mnajarro3@horizon.csueastbay.edu

**Comment by robkooper** [comment]
send a link to Michael for a different download method, waiting for a response.
