### ISSUE TITLE
From form: Testing

### ISSUE THREAD

**Issue by Pecan-Bug** [PecanProject/PecanProject.github.io#19]
Testing

*This issue was autogenerated by the Google Form for [Features](https://docs.google.com/forms/d/e/1FAIpQLSdRNat6L9grRF0xU5gibkr26xq9jD9wyHgw_AWxhrgn0lWv7w/viewform)*

Name: Rahul Agrawal

Email: rahulagrawal799110@gmail.com

**Comment by rahul799** [comment]
This issue was opened for test purposes.
