### ISSUE TITLE
Ameriflux model run is failing.

### ISSUE THREAD

**Issue by ch1eroe1** [PecanProject/PecanProject.github.io#2]
Here are the step to recreate the error I am seeing on the Ameriflux model run.
1) Open Pecan website
2)Introduction Page: Fill out nothing -> Hit Next button
3) Select host page: 
     a) Host: pecan64
     b) Model: SIPNET
     c) Site: Niwot Ridge Forest (icon near Denver, CO)
     d) Hit Next Button
4) Selected Site Page:
     a) PFTs : populus
     b) Start Date: 2004/01/01
     c) End Date: 2004/12/31
     d) Sipnet.climea : Use Ameriflux
     e) Advanced Setup: checked
     f) Hit Next Button
5) Ameriflux Data Policy -> Agree
6) Advanced Setup Page:
     a)  Runs : 2
     b) Notes : testing
     c) Hit Next Button

Results: 
Run fails on execution status page on the ensemble stage.

**Comment by mdietze** [comment]
1) Please file this issue under the PEcAn software, not the PEcAn webpage
2) Before reposting, please verify that this error persists with the conifer PFT and check to see whether it is affected by the ensemble size
3) Also, what server / VM version are you running this on?
4) Please also look at the workflow.Rout file to see what the source of the error was.
